# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/113I90Xln1yPMo3DxziswycHD4g_DsI-y
"""

from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()

DATABASE_SAHAM = []

class StockData(BaseModel):
    ticker: str
    price: float
    volume: int
    timestamp: int

@app.post("/api/v1/ingest")
def ingest_data(data: StockData):
    DATABASE_SAHAM.append(data.dict())
    return {"message": "Data berhasil disimpan"}

@app.get("/api/v1/stocks")
def get_stocks():
    return DATABASE_SAHAM